###Configmap Manifest file
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfigmap
  namespace: finlyt
data:

  SPRING_DATASOURCE_URL: jdbc:mysql://db-service:3306/finlytdb  # Database URL = .
  OLLAMA_URL: http://ollama-service:11434
  OLLAMA_MODEL: tinyllama:latest
  MYSQL_DATABASE:   finlytdb ##its name of mysql service name created by us
  MYSQL_USER: finlyt_user  # Database username.