apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc-claim
  namespace: finlyt
spec:
  storageClassName: ""
  volumeName: db-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc-claim
  namespace: finlyt
spec:
  storageClassName: ""
  volumeName: ollama-pv-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi