#### Secret manifest file

apiVersion: v1
data:
  MYSQL_PASSWORD: ZmlubHl0X3Bhc3N3b3Jk
  MYSQL_ROOT_PASSWORD: ZmlubHl0X3Jvb3RfcGFzc3dvcmQ=
kind: Secret
metadata:
  name: secret-finlyt
  namespace: finlyt
type: Opaque
